import type { MetadataRoute } from 'next'

const SITE_URL = process.env.NEXT_PUBLIC_SERVER_URL

export default function robots(): MetadataRoute.Robots {
  return {
    rules: [
      {
        userAgent: '*',
        allow: '/',
        disallow: '/admin',
      },
      {
        userAgent: [
          'DataForSeoBot/1.0',
          'bingbot',
          'seznambot',
          'LinkpadBot',
          'BLEXBot',
          'FlipboardProxy',
          'aiHitBot',
          'trovitBot',
          'grapeshot',
          'MegaIndex',
          'MJ12bot',
          'Detectify',
          'Riddler',
          'DotBot',
          'DISCo Pump',
          'Wget',
          'Teleport Pro',
          'psbot',
          'Twiceler',
          'NetinfoBot',
          'UbiCrawler',
          'DOC',
          'Zao',
          'sitecheck.internetseer.com',
          'Zealbot',
          'MSIECrawler',
          'SiteSnagger',
          'WebStripper',
          'WebCopier',
          'Fetch',
          'Teleport',
          'linko',
          'HTTrack',
          'larbin',
          'libwww',
          'ZyBORG',
          'Download Ninja',
          'grub-client',
          'NPBot',
          'WebReaper',
          'OmniExplorer_Bot',
          'Accoona',
          'Ask Jeeves',
          'WebAlta',
          'Ezooms',
          'Tourlentabot',
          'MJ12bot',
          'Nigma.ru',
          'Baiduspider',
          'Statsbot',
          'SISTRIX',
          'findlinks',
          'proximic',
          'OpenindexSpider',
          'Exabot',
          'SeznamBot',
          'oBot',
          'C-T bot',
          'Updownerbot',
          'Snoopy',
          'heritrix',
          'DomainVader',
          'Yeti',
          'DCPbot',
          'PaperLiBot',
        ],
        disallow: '/',
      },
    ],
    sitemap: `${SITE_URL}/sitemap.xml`,
  }
}
